// <auto-generated />
using System;
using Foxy.DataLayer.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Foxy.DataLayer.Migrations
{
    [DbContext(typeof(FoxyDbContext))]
    [Migration("20250616165634_initdb2")]
    partial class initdb2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Documentation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.GameCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("GameCategories");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.MatchGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("MatchGames");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.MatchMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResultType")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId");

                    b.ToTable("MatchMembers");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.StoreItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("StoreItems");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.UserGameScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("CountableMachCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastPlayDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MachCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WinCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGameScores");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.UserItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("StoreItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoreItemId");

                    b.HasIndex("UserId");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyUser.FoxyUserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeaderImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FoxyUserInfos");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.Public.HeaderImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HeaderImages");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.Support.Suggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DislikeCount")
                        .HasColumnType("integer");

                    b.Property<string>("FinalDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.Support.SuggestionVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("Like")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SuggestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SuggestionId");

                    b.HasIndex("UserId");

                    b.ToTable("SuggestionVotes");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.Support.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("tickets");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.Game", b =>
                {
                    b.HasOne("Foxy.DataLayer.Models.FoxyGame.GameCategory", "gameCategory")
                        .WithMany("games")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("gameCategory");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.MatchGame", b =>
                {
                    b.HasOne("Foxy.DataLayer.Models.FoxyGame.Game", "game")
                        .WithMany("matches")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("game");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.MatchMember", b =>
                {
                    b.HasOne("Foxy.DataLayer.Models.FoxyGame.MatchGame", "match")
                        .WithMany("matchMembers")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Foxy.DataLayer.Models.FoxyUser.FoxyUserInfo", "foxyUser")
                        .WithMany("matchMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("foxyUser");

                    b.Navigation("match");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.StoreItem", b =>
                {
                    b.HasOne("Foxy.DataLayer.Models.FoxyGame.Game", "game")
                        .WithOne("storeItem")
                        .HasForeignKey("Foxy.DataLayer.Models.FoxyGame.StoreItem", "GameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("game");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.UserGameScore", b =>
                {
                    b.HasOne("Foxy.DataLayer.Models.FoxyGame.Game", "game")
                        .WithMany("gameScores")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Foxy.DataLayer.Models.FoxyUser.FoxyUserInfo", "foxyUser")
                        .WithMany("gameScores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("foxyUser");

                    b.Navigation("game");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.UserItem", b =>
                {
                    b.HasOne("Foxy.DataLayer.Models.FoxyGame.StoreItem", "storeItem")
                        .WithMany("userItems")
                        .HasForeignKey("StoreItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Foxy.DataLayer.Models.FoxyUser.FoxyUserInfo", "foxyUser")
                        .WithMany("userItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("foxyUser");

                    b.Navigation("storeItem");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.Support.SuggestionVote", b =>
                {
                    b.HasOne("Foxy.DataLayer.Models.Support.Suggestion", "suggestion")
                        .WithMany("suggestionVotes")
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Foxy.DataLayer.Models.FoxyUser.FoxyUserInfo", "foxyUser")
                        .WithMany("suggestionVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("foxyUser");

                    b.Navigation("suggestion");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.Support.Ticket", b =>
                {
                    b.HasOne("Foxy.DataLayer.Models.FoxyUser.FoxyUserInfo", "foxyUser")
                        .WithMany("tickets")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("foxyUser");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.Game", b =>
                {
                    b.Navigation("gameScores");

                    b.Navigation("matches");

                    b.Navigation("storeItem")
                        .IsRequired();
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.GameCategory", b =>
                {
                    b.Navigation("games");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.MatchGame", b =>
                {
                    b.Navigation("matchMembers");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyGame.StoreItem", b =>
                {
                    b.Navigation("userItems");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.FoxyUser.FoxyUserInfo", b =>
                {
                    b.Navigation("gameScores");

                    b.Navigation("matchMembers");

                    b.Navigation("suggestionVotes");

                    b.Navigation("tickets");

                    b.Navigation("userItems");
                });

            modelBuilder.Entity("Foxy.DataLayer.Models.Support.Suggestion", b =>
                {
                    b.Navigation("suggestionVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
